### ISSUE TITLE
model is missing for deep learning skull stripping

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#463] opened 2019-05-01 15:44 UTC
Describe the bug
When i loaded 4 images in CaPTk and ran deep learning skull stripping with default parameters, the following pop-up appeared.
image

CaPTk Version
1.7.0

![image](https://user-images.githubusercontent.com/38562504/57025911-7a5c8c80-6c06-11e9-8f68-28b004c56836.png)

Desktop (please complete the following information):

    OS: Windows

**Comment by sarthakpati** [comment] 2019-05-06 14:22
@Geeks-Sid: FYI

**Comment by PhucNgo1711** [comment] 2019-05-10 14:59
@sarthakpati duplicate of @462 ?

**Comment by sarthakpati** [comment] 2019-05-10 15:38
Fixed in https://github.com/CBICA/CaPTk/pull/494

**Closed by sarthakpati** 2019-05-10 15:38 UTC
