### ISSUE TITLE
GeodesicTraining Command Line does not compile

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#306] opened 2019-03-04 19:01 UTC
**Describe the bug**
When building CaPTk from source, the GeodesicTraining command line does not compile and generates errors.

**To Reproduce**
1. Build CaPTk from source on Linux

**Expected behavior**
It should compile.

**Comment by dboun** [comment] 2019-03-04 20:02
Does the normal CaPTk compile? (Apart from the GeodesicTraining standalone exe)

**Comment by sarthakpati** [comment] 2019-03-04 20:10
Yes.

**Comment by dboun** [comment] 2019-03-05 14:03
The issue is fixed and the code for the fix is in a PR in Sarthak's branch.

**Closed by dboun** 2019-03-05 14:03 UTC
Labels: CLI, Linux, bug
