### ISSUE TITLE
Linux Installer

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#834] opened 2020-02-07 15:31 UTC
**Describe the bug**
The Linux installer does not install in the same directory that the installer was run in. The user needs to specify this manually. This seems to be causing some confusion with others trying to run the installer. It would be better if the default install location was in the same directory the installer was run in. 

**To Reproduce**
1. ./{captk_installer}.bin <- without specifying target dir
2. There is no new folder in the current directory

The documentation incorrectly specifies the default install location:
https://cbica.github.io/CaPTk/Installation.html

Ubuntu 18.04- Linux - 1.7.6

**Comment by PhucNgo1711** [comment] 2020-02-07 16:50
Hi,

I am aware of this bug and working on a fix.
For now please add a flag '--target {any_directory}' when running the installer. For example

`./{captk_installer}.bin --target ./My_CaPTk` will create a `My_CaPTk` directory at the current directory level and install CaPTk there.

**Comment by dboun** [comment] 2020-02-16 06:59
(this is a duplicate of #692)

**Comment by PhucNgo1711** [comment] 2020-05-17 03:11
The Linux installer now installs CaPTk at the same directory of the `./{captk_installer}.bin` if `--target` is not specified, else will install at the directory of `--target {dir}`

**Closed by PhucNgo1711** 2020-05-17 03:11 UTC
Labels: Testathon-Feb-2020
