### ISSUE TITLE
linux: warnings/errors on inital run

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#146] opened 2018-11-12 17:08 UTC
```
[bergman@huajiao ~]$ ~/CaPTk/CaPTk.bin 
QLayout: Attempting to add QLayout "" to fRegistrationDialog "fRegistrationDialog", which already has a layout
QLayout: Attempting to add QLayout "" to fRegistrationDialog "fRegistrationDialog", which already has a layout
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
Detected Size: 1969x1108
js: WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
Supplied directory name wasn't found: /datil/home/bergman/.CaPTk/1.6.0_RC_4603/tmp_6217957622668146889

```

**Comment by ashishsingh18** [comment] 2018-11-12 20:17
Fixed the QLayout warnings. The cause was incorrect parenting of child widget.

**Comment by surrsurus** [comment] 2018-11-13 15:09
- `libpng` appears to be stringent with the iCCP profiles of PNG images. While this doesn't effect anything, these broken profiles can be removed from the png images, though this isn't critical or breaking.
- The js warning is from doxygen, and since it renders in a QtWebEngine, console output that would normally be hidden in a browser is sent to the commandline.
- Detected size output is from CaPTk and this has been removed as of revision 4626.

I believe that after the fix @ashishsingh18 pushed regarding the QLayout issue, there is no further issue with these warnings.

We may want to resolve the libpng issues, which can be done with a number of methods [proposed here](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile). However the warning is not detailed at all, and doesn't alert as to which png images are suspect.

**Comment by surrsurus** [comment] 2018-11-16 14:06
Yes it is based on the version of libpng. Newer versions are more strict though they sill behave the same otherwise.

**Comment by MarkBergman-cbica** [comment] 2018-11-17 00:40
Fedora 27
Kernel  4.16.11-100.fc26.x86_64 #1 SMP Tue May 22 20:02:12 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
KDE, Plasma (5.10.5-1)
OpenGL 2.0

**Comment by PhucNgo1711** [comment] 2019-05-20 14:26
@sarthakpati same as #255 and the QLayout warnings have been fixed. Closing for now?

**Comment by sarthakpati** [comment] 2019-05-20 14:35
Fixed; closing.

**Closed by sarthakpati** 2019-05-20 14:35 UTC
Labels: Linux
