### ISSUE TITLE
Overlaying two modalities doesn't work

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#431] opened 2019-04-08 20:37 UTC
**Describe the bug**
Selecting an image and then clicking overlay on another image doesn't work.A workaround that existed in previous builds, where you click (or double click) an image, then click overlay on this image and then click overlay on another image also stopped working.

**To Reproduce** / **Expected behavior**
Steps to reproduce the target behavior:
1. Load 2+ modalities
2. Click on one image
3. Click the overlay radio button on another image

Steps to reproduce the workaround that stopped working:
1. Load 2+ modalities
2. Double click on one image
3. Click the 'Overlay' radio button on said image
4. Click the 'Overlay' radio button on another image

**CaPTk Version**
1.6.2.Beta

**Desktop:**
 - OS: Linux Mint
 - Version: 19

**Additional context**
This is very useful for brain tumors, where the only way to know what is edema is to overlay flair and t1ce.

**Comment by ashishsingh18** [comment] 2019-11-23 05:24
Duplicate of #688.

**Closed by ashishsingh18** 2019-11-23 05:24 UTC
Labels: GUI
