### ISSUE TITLE
Error message when downloading sample data

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#902] opened 2020-02-27 20:35 UTC
**Describe the bug**
When selecting the Help->Sample Data -> All
an error message is displayed
Error "Data Directory not found. Please re-install"

The download does start despite of the message.

**Screenshots**

![image](https://user-images.githubusercontent.com/47368657/75483566-20873900-5975-11ea-8537-0b360ef22a97.png)

**CaPTk Version**
1.7.6 Linux version

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10

**Comment by AlexanderGetka-cbica** [comment] 2020-02-27 21:30
I can't seem to reproduce this on my machine running ubuntu.
However, this message is only raised inside `getCaPTkDataDir()` when it can't find the data directory (which is perhaps a symptom of a larger problem with the install).

**Comment by AlexanderGetka-cbica** [comment] 2020-02-28 17:08
Tagging this as major -- while the error message itself does not impact the ability of users to download the sample data, there are two possibilities.
1. The data directory really isn't found, and a full reinstall is warranted (meaning, most likely, there is an issue with the installer or how the data directory is stored/found)
or
2. The data directory _is_ present, and this error message heavily misleads users.

**Comment by sarthakpati** [comment] 2020-03-19 17:47
Unable to replicate on current master.

**Comment by chiharusako** [comment] 2020-03-20 20:49
I believe this is an issue with the linux version. It happened both on my ubuntu and Vishnu's.

**Comment by chiharusako** [comment] 2020-03-20 20:50
Also adding that the Mac version does NOT have this issue either.

**Comment by ashishsingh18** [comment] 2020-04-03 13:54
I was able to reproduce this with 1.7.6 on Ubuntu. However it seems to be working on the latest master. Closing this, please reopen if the issue still exists.

**Closed by ashishsingh18** 2020-04-03 13:54 UTC
Labels: Major, Testathon-Feb-2020
