### ISSUE TITLE
BreastTexturePipeline: empty .csv & mask directories, error messages in CLI

### ISSUE THREAD

**Issue by ShyamDesai** [CBICA/CaPTk#911] opened 2020-02-28 20:45 UTC
**Describe the bug**
Attempted to run the BreastTexturePipeline module on a single DICOM image. Output seems fine at first, LIBRA executes and runs. Produces the following error in CLI with debug option:  

MATLAB was unable to run the matlab_helper executable, which the ! and
unix() commands require.  You may have an incomplete installation or
permission problems with /gpfs/fs001/cbica/software/lab/captk/centos7/1.7.6/libexec/MCR/v84/bin/glnxa64/matlab_helper

MATLAB was unable to run the matlab_helper executable, which the ! and
unix() commands require.  You may have an incomplete installation or
permission problems with /gpfs/fs001/cbica/software/lab/captk/centos7/1.7.6/libexec/MCR/v84/bin/glnxa64/matlab_helper
images:dicom_generate_uid:linuxSystemProblem
Could not generate UID.
   > libra_exper failed.
Libra did not succeed. Please recheck.

**To Reproduce**
1. ssh -X username@cbica-cluster
2. module unload captk
3. module load captk/1.7.6
4. /cbica/software/lab/captk/centos7/1.7.6/bin/BreastTexturePipeline -i /cbica/home/desaish/Tomo/Dx_images/PROC_Mammo/3009186/3009186_L_CC_1.dcm -o /cbica/home/desaish/Tomo/Dx_results/PROC_Mammo -d 1

**Expected behavior**
Pipeline should start pre-processing, Run LIBRA, and then write output to csv and create a DICOM mask. Creates a 'temp' directory with empty Density.csv file and empty Result_images file within.

CaPTk Version
1.7.6 Testathon

Desktop (please complete the following information):
Windows 10 Enterprise, Version 1809
OS Build 17763.973

**Comment by sarthakpati** [comment] 2020-02-29 14:40
Thank you for the report, @ShyamDesai!

So, this seems to be a duplicate of #584, which for some reason has recurred:

```bash
(base) patis@/cbica/home/patis>$ ls -l /gpfs/fs001/cbica/home/patis/testing/captkMyForkInstall/libexec/MCR/v84/bin/glnxa64/matlab_helper
-rw-r--r--. 1 patis cbica 99163 Nov 27 22:23 /gpfs/fs001/cbica/home/patis/testing/captkMyForkInstall/libexec/MCR/v84/bin/glnxa64/matlab_helper
```

The commit https://github.com/sarthakpati/CaPTk/commit/3d0bb079b19b1f44134a4e0c138895153a71b2c2 should have fixed this. Unsure why the permission change is not going through...

**Comment by sarthakpati** [comment] 2020-02-29 19:31
Fixed:

```bash
(base) patis@/cbica/home/patis/testing/captkMyForkInstall>$ ls -l ./libexec/MCR/v84/bin/glnxa64/matlab_helper
-rwxr-xr-x. 1 patis cbica 99163 Nov 27 22:23 ./libexec/MCR/v84/bin/glnxa64/matlab_helper*
```

I am still investigating how this happened. Once I find out more, I will post details. But this issue should be fixed, so closing issue.

**Closed by sarthakpati** 2020-02-29 19:31 UTC
Labels: Testathon-Feb-2020
