### ISSUE TITLE
Windows Smartscreen warning

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#1216] opened 2020-07-31 15:34 UTC
On starting the installer.

-----------

OS Name Microsoft Windows 10 Home
Version 1903
OS Build 18362.959

System Manufacturer HP
System Model HP Spectre x360 Convertible
System Type x64-based PC
Processor Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date American Megatrends Inc. F.07, 14-Apr-16
SMBIOS Version 2.8
Embedded Controller Version 38.22
BIOS Mode UEFI

![windows protected your pc](https://user-images.githubusercontent.com/43213897/89051071-af7fef00-d321-11ea-9027-19a8084af636.PNG)

**Comment by AlexanderGetka-cbica** [comment] 2020-07-31 18:35
I can replicate this on my machine as well. Clicking "more info" and then selecting "Run Anyway" or similar should allow you to run it. 

 In order for us to address this we probably need to add some sort of application signing. After doing some further research, even standard code signing requires a larger userbase to establish reputation unless we purchase an Extended Validation certification from a certificate authority [[ref](https://security.stackexchange.com/questions/139347/smart-screen-filter-still-complains-despite-i-signed-the-executable-why)].

**Comment by sarthakpati** [comment] 2020-07-31 19:20
Duplicate of #47. We can continue the conversation in a single place, henceforth.

**Closed by sarthakpati** 2020-07-31 19:20 UTC
