### ISSUE TITLE
DICOM to NIFTI

### ISSUE THREAD

**Issue by DushyantSahoo** [CBICA/CaPTk#862] opened 2020-02-17 19:53 UTC
**Describe the bug**
When I am trying to convert DICOM to NIFTI, I get the below error after giving the path of the images-
"Couldn't convert the DICOM with the default parameters; please use command line functionality"

It was running correctly few days back, then abruptly this error started coming.

**To Reproduce**
1. Go to 'Preprocessing'
2. Click on 'DICOM to NIFTI'
3. Give path of images
4. Error

**Expected behavior**
DICOM images should be converted to NIFTI image

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version (including Build information, if any): 16.04

**Comment by ashishsingh18** [comment] 2020-02-20 15:26
@DushyantSahoo Can you please re-check step 3 to reproduce in your description. Currently a user cannot select images. Only folder selection is allowed. Also can you please check if the folder you selected had any data? And could you please share the path to the data that was giving this error, on the cluster ?

**Comment by DushyantSahoo** [comment] 2020-02-26 17:57
@ashishsingh18 The error is same- "Couldn't convert the DICOM with the default parameters; please use command line functionality". Yes, I am not selecting images, I am selecting a folder and that folder has dicom images. I am running this on my desktop.

**Comment by DushyantSahoo** [comment] 2020-02-26 18:58
On the terminal the error is- "tmp/.mount_captkTSpyaj/usr/bin/dcm2nii: not found"

**Comment by ashishsingh18** [comment] 2020-02-26 19:53
@DushyantSahoo Could you please point me to the data on the cluster?

**Comment by ashishsingh18** [comment] 2020-02-27 19:48
@DushyantSahoo We got some data from @chiharusako but are still not able to replicate this issue.

Is this occuring for just one specific data or for all datasets?

It seems that this is something specific to your machine. If you are around we will need to sit with you to try some more things. 

Also tagging @AlexanderGetka-cbica

**Comment by AlexanderGetka-cbica** [comment] 2020-02-27 20:53
Developer notes:
- The only way for the  `Couldn't convert the DICOM with the default parameters; please use command line functionality` error to be raised is if `cbica::ReadImage(inputDir)` DICOM reading returns a nullptr (fails). Functionally, this issue only happens if CaPTk defers to the dcm2nii executable because cbica::ReadImage fails to handle the DICOM.

- We do not output to the terminal between calling `startExternalProcess` and getting the result from the external process. The `tmp/.mount_captkTSpyaj/usr/bin/dcm2nii: not found` error is output to the terminal specifically by the system call (it can't find the target specified by `fullCommandToRun` which in turn is defined in expanded form by `cbica::normPath("." + QApplication::applicationDirPath() + "/dcm2nii")` where `applicationDirPath()` returns the directory the executable is running from and `cbica::normPath()` appears to "normalize a path name by collapsing redundant separators and up-level references". It is _very_ odd that this results in a path from tmp, so this warrants more investigation.

- We noticed that symlinks were involved when Dushyant was loading the DICOMs and thought this may be related. However, I tested this with both file symlinks and directory symlinks in the path and I couldn't reproduce the issue this way.

**Comment by ashishsingh18** [comment] 2020-03-20 21:34
@DushyantSahoo Is this still an issue? I haven't been able to replicate this.

**Comment by ashishsingh18** [comment] 2020-03-23 14:26
Closing this as we are unable to replicate. Please reopen if necessary.

**Closed by ashishsingh18** 2020-03-23 14:26 UTC
Labels: Testathon-Feb-2020
