### ISSUE TITLE
Linux installer cannot find  ./linux-installer: No such file or directory

### ISSUE THREAD

**Issue by sungminhacbica** [CBICA/CaPTk#243] opened 2019-02-05 20:40 UTC
## Expected Behavior

CaPTk 1.6.1 installs correctly after running the downloaded CaPTk_1.6.1bin file.

## Actual Behavior

Produces the following message:
$ chmod 755 CaPTk_1.6.1.bin 
$ bash CaPTk_1.6.1.bin 
Verifying archive integrity...  100%   All good.
Uncompressing CaPTk Linux Installer  100%  
CaPTk_1.6.1.bin: line 578: ./linux-installer: No such file or directory

## Steps to Reproduce the Problem

  1. Download from the CaPTk_1.6.1bin file with wget on terminal with the link "https://www.nitrc.org/frs/downloadlink.php/11129"
  2. `chmod 755 CaPTk_1.6.1bin`
  3. bash CaPTk_1.6.1bin

## Specifications

  - Version: CaPTk_1.6.1bin, downloaded from "https://www.nitrc.org/frs/downloadlink.php/11129"
  - Platform: Linux (copying lsb_release -a below)
`No LSB modules are available.`
`Distributor ID:	Ubuntu`
`Description:	Ubuntu 18.04.1 LTS`
`Release:	18.04`
`Codename:	bionic`
  - Subsystem: ??

**Comment by chiharusako** [comment] 2019-02-05 20:59
I have the same issue with installing the linux CaPTk_1.6.1 downloaded by:
- wget ftp://www.nitrc.org/home/groups/captk/downloads/CaPTk_1.6.1.bin

Error message:
$ ./CaPTk_1.6.1.bin 
Verifying archive integrity...  100%   All good.
Uncompressing CaPTk Linux Installer  100%  
./CaPTk_1.6.1.bin: 1: eval: ./linux-installer: not found

Linux version:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

**Comment by surrsurus** [comment] 2019-02-06 17:05
I know the exact issue. The installer is trying to pick up the install script but it can't find it, I've fixed the issue, verified it on my machine, and will report back when the download link is updated. This is an issue with the Linux packaging step, so the issue is only caught on install time.

**Comment by surrsurus** [comment] 2019-02-08 12:47
This issue has been resolved, and the download link has been updated. If there continues to be any more issues, comment on this issue and we can re-open it.

**Comment by omaghsoudi** [comment] 2019-02-14 15:35
Hi all, 

I am trying to install CaPTK on Ubuntu 18.04, and it gives me the same error (eval: ./linux-installer: not found).
I got the latest version, CaPTk_1.6.1. 

Should I try any other versions?

**Comment by surrsurus** [comment] 2019-02-14 15:51
Do another download of the installer, as you might not have the updated one.

**Comment by activegalaxy** [comment] 2019-02-14 16:06
I downloaded Linux version yesterday and apparently the linux-installer problem is fixed.

**Comment by omaghsoudi** [comment] 2019-02-14 16:22
That is true, the newest version works. 
I think I downloaded the CaPTK a few days ago and it didn't work. 

I close the issue. Thank you!

**Closed by omaghsoudi** 2019-02-14 16:22 UTC
Labels: Linux, packaging

**Comment by MarkBergman-cbica** [comment] 2019-02-14 17:28
Can you please provide results from the following command:
`
sh CaPTk_1.6.1.bin --info`

**Comment by omaghsoudi** [comment] 2019-02-14 17:35
Hi Mark,

This is the results for the version which worked for me:


Identification: CaPTk Linux Installer
Target directory: pkg
Uncompressed size: 958308 KB
Compression: gzip
Date of packaging: Wed Feb 6 12:02:46 EST 2019
Built with Makeself version 2.4.0 on
Build command was: ./makeself-2.4.0/makeself.sh \
    "--gzip" \
    "pkg/" \
    "CaPTk_1.6.1_Installer.bin" \
    "CaPTk Linux Installer" \
    "./linux-makeself"
Script run after extraction:
     ./linux-makeself
pkg will be removed after extraction


Bests,
Omid
