### ISSUE TITLE
DICOM to NIFTI CLI invokes HDF5 from source superbuild macOS

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#1070] opened 2020-06-02 20:28 UTC
**Describe the bug**
Running DICOM to NIFTI from the GUI works, but running the CLI invokes `ITK-source/Modules/ThirdParty/HDF5` at the superbuild location inside `cbica-osx3`

**To Reproduce**
1. Run the command `${CaPTk_InstallDir}/bin/Utlities -i ${Your_Data_Dir}/dicomFolderWithSingleSubject -o ${Your_Output_Dir}/PathToOutputFolder/result.nii.gz -d2n 
`
**Expected behavior**
It should produce a NIFTI image like the GUI

**Screenshots**
![Screen Shot 2020-06-02 at 4 27 47 PM](https://user-images.githubusercontent.com/14838084/83566447-0322b780-a4ee-11ea-9c49-078b8c8573be.png)

**CaPTk Version**
1.8.0 Alpha

**Desktop (please complete the following information):**
 - OS: macOS
 - Version (including Build information, if any): 10.13, 10.14

**Comment by sarthakpati** [comment] 2020-06-02 20:29
Check if this works:

https://github.com/CBICA/CaPTk/issues/1060#issuecomment-637784018

**Comment by PhucNgo1711** [comment] 2020-06-02 20:40
@sarthakpati Ah that fixed it! So just a check for directory and a message should do the trick then.

**Comment by sarthakpati** [comment] 2020-06-02 20:55
Already done.

**Comment by sarthakpati** [comment] 2020-06-02 20:56
Duplicate of #1060

**Closed by sarthakpati** 2020-06-02 20:55 UTC
Labels: CLI, bug, macOS
