### ISSUE TITLE
ComparisonMode did not work with 4 images

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#470] opened 2019-05-01 16:14 UTC
i loaded 4 images in CaPTk and selected 'ComparisonMode' from the top right corner, CaPTk crashed.

**Comment by ashishsingh18** [comment] 2019-05-06 14:52
I am not able to reproduce this. It works on 2 different machines that we tried on.

**Comment by ashishsingh18** [comment] 2019-05-06 15:29
Tried it on Mac OS and still can't reproduce the issue.

**Comment by ashishsingh18** [comment] 2019-05-06 15:29
Closing the issue. If we see it again, we will reopen it.

**Closed by ashishsingh18** 2019-05-06 15:29 UTC
