### ISSUE TITLE
Loading CaPTk on cluster

### ISSUE THREAD

**Issue by ChitaliaR** [CBICA/CaPTk#874] opened 2020-02-20 16:34 UTC
**Describe the bug**
When trying to load CaPTk on the cluster using:  module load captk/1.7.6, an error message appears saying no such file or directory

**To Reproduce**
1. On cluster type: module load captk/1.7.6 
2. type: captk

**Expected behavior**
captk should load

**Error message **
WARNING: Trying to run CaPTk GUI using software rendering - this might not work on all systems and in those cases, only the CLI will be available.
[0220/113047.396168:WARNING:stack_trace_posix.cc(699)] Failed to open file: /scratch/chitalir/#5898244 (deleted)
  Error: No such file or directory
qt.qpa.xcb: QXcbConnection: XCB error: 145 (Unknown), sequence: 175, resource id: 0, major code: 139 (Unknown), minor code: 20
 ApplicationPreferences::DisplayPreferences()

 font =  ""

 theme =  ""

 ApplicationPreferences::DisplayPreferences()

 font =  "Sans Serif,9,-1,5,50,0,0,0,0,0"

 theme =  "Dark"

 ApplicationPreferences::DisplayPreferences()

 font =  "Sans Serif,9,-1,5,50,0,0,0,0,0"

 theme =  "Dark"

p11-kit: couldn't list directory: /etc/pki/ca-trust/source/anchors: Permission denied
The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Success) on X server "170.166.98.52:16.0"
      after 710 requests (710 known processed) with 0 events remaining.

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Windows

**Comment by ashishsingh18** [comment] 2020-02-20 16:49
Related to #831

**Comment by dboun** [comment] 2020-02-20 19:32
Duplicate of #831

**Closed by dboun** 2020-02-20 19:32 UTC
Labels: Testathon-Feb-2020, wontfix
