### ISSUE TITLE
breastDensityEstimation(Single Image) is not running the way it si expected to do

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#464] opened 2019-05-01 15:57 UTC
loaded on mammogram image from sample data
(case1.dcm)
Selected breastDensityEstimation(Single Image)  from the applications menu. Got the following error message. 

![image](https://user-images.githubusercontent.com/38562504/57026495-fdcaad80-6c07-11e9-9b69-11e33413e1ea.png)

Windows 7

**Comment by ashishsingh18** [comment] 2019-05-02 16:16
Duplicate of #474

**Closed** 2019-05-07 21:11 UTC
