### ISSUE TITLE
Can't build linux installer on newer OS

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#482] opened 2019-05-06 16:11 UTC
**Describe the bug**
When trying to locally build the linux installer from CaPTk superbuild, an error comes up claiming the OS is too new (Ubuntu 18.10).  No problems are encountered when building for Ubuntu 16.04

**To Reproduce**
1. Go to CaPTk root directory
2. Run ./scripts/captk-pkg
3. Wait until error comes up

**Expected behavior**
CaPTk_1.7.0.Alpha_Installer.bin would be generated in the CaPTk root directory

**Screenshots**
![too_new](https://user-images.githubusercontent.com/20047333/57238002-647c0c80-6ff6-11e9-907b-c2f4c9214ce0.PNG)

**CaPTk Version**
1.7.0

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - 18.10

**Comment by sarthakpati** [comment] 2019-05-06 16:15
Please follow along the related (open) thread on LinuxDeployQt's issues page: https://github.com/probonopd/linuxdeployqt/issues/340

**Comment by sarthakpati** [comment] 2019-05-06 16:43
Duplicate of #481

**Comment by sarthakpati** [comment] 2019-05-06 16:44
Possibly related to #481

**Comment by jminock** [comment] 2019-05-07 20:47
Mark had the idea for on newer OS's (newer than Ubuntu 16.04) the captk-pkg (or cmake) generates a warning message explaining the issue with LinuxDeployQt and does not include packaging.  For appropriate OS's, everything runs as is.

**Comment by sarthakpati** [comment] 2019-05-07 21:13
That's an excellent idea, @jminock! I am not sure what would be the most appropriate way to check for "newer" Linux distros. Perhaps @MarkBergman-cbica could point us how?

**Comment by MarkBergman-cbica** [comment] 2019-05-07 21:36
In the message dated: Tue, 07 May 2019 14:13:35 -0700,
The pithy ruminations from Sarthak Pati on 
[[External] Re: [CBICA/CaPTk] Can't build linux installer on newer OS (#482)] were:
=> That's an excellent idea, @jminock! I am not sure what would be the most appropriate way to check for "newer" Linux distros. Perhaps @MarkBergman-cbica could point us how?


Well, I guess the idea of "newer" should follow the same rules as AppImage, whatever those are.

Parsing distribution names or numbers is not the right approach.

For the GLIBC version, I'd use the output of "ldd", something like:
	ldd --version | sed -n -e "s/^ldd .* //p"

Mark

=> 
=> -- 
=> You are receiving this because you were mentioned.
=> Reply to this email directly or view it on GitHub:
=> https://github.com/CBICA/CaPTk/issues/482#issuecomment-490257580

-- 
Mark Bergman                                           voice: 215-746-4061       
mark.bergman@pennmedicine.upenn.edu                      fax: 215-614-0266
http://www.med.upenn.edu/cbica/
IT Technical Director, Center for Biomedical Image Computing and Analytics
Department of Radiology                         University of Pennsylvania

**Comment by sarthakpati** [comment] 2019-05-07 22:15
A slightly more comprehensive check as been added. Testing this fix now.

**Comment by sarthakpati** [comment] 2019-05-08 04:27
The first pass worked (the version checker passed through the Azure Pool and built the package, which was expected). Need to be tested on a newer Linux.

**Comment by jminock** [comment] 2019-05-08 18:34
It works, but it continues to attempt to build the installer which results in an error that it cannot find 'CaPTk.bin'

![too_new_2](https://user-images.githubusercontent.com/20047333/57398900-199cf900-719e-11e9-9f70-ae7c67d5f70f.PNG)

**Comment by sarthakpati** [comment] 2020-07-01 16:15
Newer Linux distros cause issue with AppImage, so closing.

**Closed by sarthakpati** 2020-07-01 16:15 UTC
Labels: Linux, Packaging
