### ISSUE TITLE
CaPTk continues to access files in build directory after installation

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#881] opened 2020-02-21 15:49 UTC
Example:

The installed version of CaPTk on  CUBIC (built by Sarthak, but installed system-wide) is trying to access files in /cbica/home/patis.

Running

```
	module load captk/1.7.6
	strace -f -o captk.strace captk Deepmedic -t1 ./MR_T1_image.nii.gz -t1c ./MR_T1_image.nii.gz -t2 ./MR_T1_image.nii.gz -fl ./MR_T1_image.nii.gz -o output_dir -md $CAPTK_DIR/data/deepMedic/saved_models/skullStripping
```

produces a list of system calls in the file 'captk.strace'. That shows:

```
	41616 stat("/cbica/home/patis/projects/CaPTk_master/data/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
and
	41677 execve("/gpfs/fs001/cbica/software/lab/captk/centos7/1.7.6/bin/DeepMedic/gpfs/fs001/cbica/home/deepMedicRun", ["/gpfs/fs001/cbica/software/lab/c"..., "-t1", "output_dir/t1_normalized.nii.gz", "-t1c", "output_dir/t1ce_normalized.nii.g"..., "-t2", "output_dir/t2_normalized.nii.gz", "-fl", "output_dir/fl_normalized.nii.gz", "-model", "/cbica/software/lab/captk/centos"..., "-load", "/cbica/software/lab/captk/centos"..., "-test", "/cbica/home/patis/projects/CaPTk"..., "-o", "output_dir"], [/* 258 vars */]) = -1 ENOTDIR (Not a directory)
```

The first system call succeeds. If the second one did not fail (due to the incorrect construction of the path to the executable), then it would have referenced data in Sarthak's directory. This is a serious issue, as CaPTk could produce incorrect results lab-wide if Sarthak alters his testing data, thinking it is private to his development.

There are 2 things to be addressed:

	1. The process of building CaPTk from source & installing it should produce executables that continue to reference the build directory

	2. There is a bug in the construction of the path for commands to be execve()'d.

**Comment by sarthakpati** [comment] 2020-02-21 19:15
Was the installation done using the ```make install/strip``` command?

**Comment by sarthakpati** [comment] 2020-02-21 19:17
Point #2 is not replicable (see my latest reply to the RT ticket 1354).

**Comment by MarkBergman-cbica** [comment] 2020-02-21 20:02
> Was the installation done using the `make install/strip` command?

Yes.

**Comment by sarthakpati** [comment] 2020-02-21 20:46
I ran DM distributed in 1.7.6 and I didn't find any reference to the path you mention in 1; at least nothing unexpected:

```bash
(base) patis@/cbica/home/patis>$ strace -f -o captk.strace captk DeepMedic -t1 ~/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz -t1c ~/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz -t2 ~/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz -fl ~/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz -md ~/projects/captk_myFork/data/deepMedic/saved_models/skullStripping/ -o ~/testing/dmOut/

[SNIP!]

(base) patis@/cbica/home/patis>$ cat captk.strace | grep -i data | grep stat
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/deepMedic/saved_models/skullStripping", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/gpfs/fs001/cbica/software/lab/captk/centos7/1.7.6/bin/../data/", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
25569 stat("/scratch/patis/_MEIw939vO/unicodedata.cpython-36m-x86_64-linux-gnu.so", 0x7fff75dbad00) = -1 ENOENT (No such file or directory)
25569 stat("/scratch/patis/_MEIw939vO/lib2to3/tests/data", 0x7fff75dbad00) = -1 ENOENT (No such file or directory)
25569 stat("/scratch/patis/_MEIw939vO/lib2to3/tests/data/README", 0x7fff75dbad00) = -1 ENOENT (No such file or directory)
25605 lstat("/scratch/patis/_MEIw939vO/nibabel/tests/data", 0x7ffea439d540) = -1 ENOENT (No such file or directory)
25569 stat("/scratch/patis/_MEIw939vO/lib2to3/tests/data", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
25569 stat("/scratch/patis/_MEIw939vO/lib2to3/tests/data/README", {st_mode=S_IFREG|0700, st_size=404, ...}) = 0
25569 stat("/scratch/patis/_MEIw939vO/unicodedata.cpython-36m-x86_64-linux-gnu.so", {st_mode=S_IFREG|0700, st_size=913304, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
25562 stat("/cbica/home/patis/projects/captk_myFork/data/AAAC0_flair_pp_shrunk.nii.gz", {st_mode=S_IFREG|0644, st_size=301273, ...}) = 0
```

**Comment by sarthakpati** [comment] 2020-02-22 23:55
Point 2 is duplicate of #879

**Closed** 2020-06-25 20:30 UTC
Labels: blocking
