### ISSUE TITLE
Self-hosted macOS build issues

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1031] opened 2020-05-15 13:29 UTC
**Describe the bug**

All details are for this run: https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1463&view=logs&jobId=79636c1a-aae7-5b3a-7853-8a6d3a41631c&j=79636c1a-aae7-5b3a-7853-8a6d3a41631c&t=97e6077b-5065-54f1-420d-a225053560e5

**Comment by PhucNgo1711** [comment] 2020-05-15 14:21
I've found the cause. I'm working on a fix for this. The self-hosted build created a new folder structure outside of the root CaPTk source and CMake was picking up the old structure.

**Comment by PhucNgo1711** [comment] 2020-05-17 03:12
This is now fixed.

**Closed by PhucNgo1711** 2020-05-17 03:12 UTC
Labels: Azure Pipeline, Critical
