### ISSUE TITLE
opacity/overlay functionality is not working

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#688] opened 2019-11-05 15:47 UTC
**Describe the bug**
opacity/overlay functionality is not working

**To Reproduce**
Load 2 images.
Click on Opacity radio button
check "change opacity"
slider does not show both 2 images but is just slightly changes the intensity of 1 image

**CaPTk Version**
1.7.2

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by sarthakpati** [comment] 2019-11-13 15:57
This is also present in 1.7.3.Beta

**Comment by sarthakpati** [comment] 2019-11-21 16:42
Duplicate of #431

**Comment by ashishsingh18** [comment] 2020-01-27 17:40
Done.

**Closed by ashishsingh18** 2020-01-27 17:40 UTC
Labels: Critical, Rendering
