### ISSUE TITLE
Linux pre-installation check for FUSE is faulty, installs when FUSE is not present. Insufficient documentation re. appimage-extract option.

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#506] opened 2019-05-14 16:54 UTC
```

[bergman@cbica-cluster comp_space]$ sh ./CaPTk*bin
Verifying archive integrity...  100%   All good.
Uncompressing CaPTk Linux Installer  100%  
By installing the Cancer and Phenomics Toolkit (CaPTk), the user agrees to the following licenses, which pertain to the code and its different constituents:

1. SBIA Software License - https://www.med.upenn.edu/sbia/software-agreement.html
2. SBIA Non-Commercial Software License (applies to PHI Estimator) - https://www.med.upenn.edu/sbia/software-agreement-non-commercial.html
3. Insight Toolkit License - https://cmake.org/Wiki/ITK/License_Information
4. Visualization Toolkit License - http://www.vtk.org/licensing/
5. Qt Open Source License - https://doc.qt.io/qt-5.10/qtcore-index.html#licenses-and-attributions; our copy can be found at https://github.com/CBICA/qt
6. CC Attribution-ShareAlike for SRI24 data - https://creativecommons.org/licenses/by-sa/3.0/us/legalcode 
7. MRIcroGL License - BSD
8. YAML-CPP - MIT License and can be found at https://opensource.org/licenses/MIT
9. Eigen - MPL2 License and can be found at https://www.mozilla.org/en-US/MPL/2.0/

I accept the terms of the licenses above [Y/N] y
Creating ~/CaPTk/...
Creating ~/CaPTk/1.7.0.Beta/...
Checking disk space...
Checking for FUSE...
Installing... /
Installing CWL
Creating symbolic link 'captk'
Done.
To run CaPTk, enter the command "~/CaPTk/1.7.0.Beta/captk" in your console.
[bergman@cbica-cluster comp_space]$ ~/CaPTk/1.7.0.Beta/captk
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
[bergman@cbica-cluster comp_space]$ 
```

What is the purpose/intended response from the pre-installation check for FUSE? If the check fails, does the installer exist, or should it continue? If it should continue, then it **must** give clear information to the user to the user at that point (and ideally replace the instruction about running CaPTk with a command-line example about running CaPTk with the 'appimage-extract' option).

Running:

```~/CaPTk/1.7.0.Beta/captk --appimage-extract``` 

succeeds in extracting the files, but doesn't immediately launch CaPTk or instruct the user what to do next.

**Comment by sarthakpati** [comment] 2019-05-15 00:01
Same as #257, was fixed in #263

I am not sure what extra we can do here other than adding a full customized checking script for CaPTk before it runs for Linux. Currently, the pre-installation check is happening [here](https://github.com/CBICA/CaPTk/blob/master/scripts/linux-makeself#L66). I am not 100% sure if I can find a way to improve it further, to be honest.

**Comment by MarkBergman-cbica** [comment] 2019-05-15 00:21
First, the FUSE check is incorrect. As shown above, the check does **not**  display the message "Warning: FUSE is not installed....". The shell script is testing for the success or failure of setting a variable:
`fusefail=0`
not for the status of the command "fusermount". The order of those lines needs to be reversed.


More importantly, my suggestions were to improve the FUSE check via documentation -- if the check fails, the user should be informed then about how to extract the files from the app image and how to run CaPTk -- or the installation should exit out at that point. As is, the "install" finishes, leaving the user without CaPTk installed and with a vague instruction about using the "--appimage-extract" option...which isn't helpful.

**Comment by MarkBergman-cbica** [comment] 2019-05-15 00:45
Have you extracted the files with the option "--appimage-extract" option? 

By itself, that is not a useful instruction for users.

1. It doesn't clearly state what command to run.
2. It provides no guidance on what to do after running that command.

We need to either provide simple, clear, comprehensive instructions for what to do in the absence of FUSE, or give a clear error message during the pre-installation check that FUSE is required and that nothing will be installed and then exit -- completely eliminating the info about extracting files.

**Comment by sarthakpati** [comment] 2019-05-15 02:46
Does the warning message illustrated in the latest commit [[ref](https://github.com/sarthakpati/CaPTk/commit/2070d41756de911be5f361b20a89677916cc83fd#diff-d20c9ebdbdbb0c2f985db13736646a47L116)] highlight the warning in a better way?

**Comment by sarthakpati** [comment] 2019-05-15 03:13
> Does the warning message illustrated in the latest commit [[ref](https://github.com/sarthakpati/CaPTk/commit/2070d41756de911be5f361b20a89677916cc83fd#diff-d20c9ebdbdbb0c2f985db13736646a47L116)] highlight the warning in a better way?

Also, how does adding an FAQ section in Readme:

- [LINUX]: If the installer successfully finishes and you are not able to run CaPTk due to FUSE issues, please extract the installer using the following command to extract the contents of the AppImage onto the hard drive:
```bash
user@pc:~# ~/CaPTk/${version}/captk --appimage-extract
```

**Comment by MarkBergman-cbica** [comment] 2019-05-15 16:13
>     * [LINUX]: If the installer successfully finishes and you are not able to run CaPTk due to FUSE issues, please extract the installer using the following command to extract the contents of the AppImage onto the hard drive: `user@pc:~# ~/CaPTk/${version}/captk --appimage-extract`

That is accurate, but not helpful. From an end-user's perspective:

1. The CaPTk installation "failed"
2. Running a command produced a tremendous amount of output on-screen, none of which was meaningful.
3. After running "appimage-extract" there is no information about how to proceed to execute CaPTk itself.

**Comment by sarthakpati** [comment] 2019-05-15 16:17
The installation is handled by `AppImage` and `makeself`. How do you propose we handle this?

**Comment by MarkBergman-cbica** [comment] 2019-06-12 16:59
At the very least, we must provide comprehensive steps to using the applications after extracting them. That may include setting variables (LD_LIBRARY_PATH, PATH), example CLI usage, etc. We may need to provide wrappers (shell scripts, static binaries without external dependencies) that correctly set the environment relative to the location of the extracted files and then exec() the CLI application.

**Comment by sarthakpati** [comment] 2019-06-13 16:06
Agreed. The issue is that then we will need to maintain 2 different deployments for Linux. @PhucNgo1711 thoughts?

**Comment by PhucNgo1711** [comment] 2019-06-13 16:23
Yeah I think 2 deployments is easier to keep track of changes

**Comment by sarthakpati** [comment] 2019-06-13 18:59
I guess this will need to get added to Azure. @PhucNgo1711 we can discuss this in person tomorrow.

**Comment by MarkBergman-cbica** [comment] 2020-06-24 19:20
Is this still an open issue, or #545 a solution?

**Comment by sarthakpati** [comment] 2020-06-24 19:27
> Is this still an open issue, or #545 a solution?

Should be.

https://cbica.github.io/CaPTk/FAQ.html#gs_FAQ_5_1

**Closed by sarthakpati** 2020-06-24 19:27 UTC
Labels: Linux, Packaging, blocking
