### ISSUE TITLE
Writing dicom from nifti flips the image [Command Line]

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#913] opened 2020-02-28 21:45 UTC
**Describe the bug**
Using -n2d in utilities flips the image

**To Reproduce**

Go to /cbica/home/sharmapa/comp_space/Testathon/nifti/ACSL

Command 
>captk Utilities -i ACSL_2019.02.28_t1.nii.gz -o ../../N2D/ACSL/ -n2d ../../dicoms/ACSL/ACSL_2019.02.28_t1/

**Screenshots**
Original Dicom

![ACSL_1_original_dcm](https://user-images.githubusercontent.com/58265133/75589574-21899a80-5a49-11ea-9c54-2c22992cdca7.png)

Original Nifti
![ACSL_2_original_nifti](https://user-images.githubusercontent.com/58265133/75589608-323a1080-5a49-11ea-818b-f8098bed2471.png)

Niffti to Dicom conversion using -n2d

![ACSL_3_convertbacktodcm](https://user-images.githubusercontent.com/58265133/75589725-8d6c0300-5a49-11ea-8d61-608e09d7452f.png)

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Linux on cluster

**Comment by ashishsingh18** [comment] 2020-03-02 04:30
@parthsharma853 I have been unable to replicate this with other data sets. I still need to try this with the specific data you referred.

**Comment by chiharusako** [comment] 2020-03-10 18:22
@sarthakpati I thought we fixed this in #676 . Was the change merged?

**Comment by sarthakpati** [comment] 2020-03-10 19:55
@chiharusako We had tested it on a bunch of images after merging in https://github.com/sarthakpati/CaPTk/commit/d796e1f75e4e09e49528f57a3b9a23f278add505

**Comment by chiharusako** [comment] 2020-03-10 20:09
@sarthakpati I can replicate this flip also, and I'm not sure why because I thought I tested back then also.

@parthsharma853 - please provide @ashishsingh18 with the data, outside this thread as it involves dicoms

**Comment by ashishsingh18** [comment] 2020-03-10 21:10
@chiharusako Nifti to dicom conversion is not an easy problem because Nifti doesn't have all the metadata that a dicom requires. The method that we currently have has bigger problems than just image flip. If incorrect reference dicoms are supplied, it is highly likely to fail.

**Comment by chiharusako** [comment] 2020-03-11 14:03
@ashishsingh18 Thanks for looking into this functionality as it is important for the lab. Here is an example. No new reference dicom is introduced.

1. Anonymized TCGA dicom - to Nifti 
2. This Nifti back to dicom

Files are in: /cbica/home/sakoc/comp_space/lab/captk/1.7.6/nifti2dcm

To reproduce:
1. Original dicom to nifti 19970608090647_AX_FLAIR_11.nii.gz	
/cbica/home/sakoc/software/dcm2niix/v1.0.20190410/dcm2niix -o . -z y -f %t_%p_%s 1_TCGA-02-0003_1997.6.8_flair

2. 19970608090647_AX_FLAIR_11.nii.gz to dicom in 2_nifti2dcm_TCGA-02-0003_1997.6.8_flair
/cbica/software/lab/captk/centos7/1.7.6/bin/Utilities -n2d 1_TCGA-02-0003_1997.6.8_flair -i 19970608090647_AX_FLAIR_11.nii.gz -o /cbica/home/sakoc/comp_space/lab/captk/1.7.6/nifti2dcm/2_nifti2dcm_TCGA-02-0003_1997.6.8_flair

@parthsharma853 no worries for sending the other data as I've sent this anonymized one

**Comment by ashishsingh18** [comment] 2020-03-20 20:40
@chiharusako I am unable to reproduce this even with the data you shared.

**Comment by chiharusako** [comment] 2020-03-20 20:46
@ashishsingh18  Can you try on the linux version on the cluster? That's the one both Parth and I used.

**Comment by ashishsingh18** [comment] 2020-03-21 00:37
@chiharusako my cluster account is behaving weird. However I tried on Ubuntu and it works fine. How are you converting the dicom to nifti in the first step?

**Comment by chiharusako** [comment] 2020-03-24 17:20
we're using dcm2niix v1.0.20190410

**Comment by ashishsingh18** [comment] 2020-03-24 20:11
@chiharusako I tried this on the cluster and it works fine. I didn't use dcm2niix. I did the dicom to nifti conversion on my windows machine using captk and transferred that nifti to the cluster and then did the n2d. It worked fine.

**Comment by chiharusako** [comment] 2020-03-24 21:36
This is good information. 

Now I see that the difference of the nifti output of dcm2niix and the dicom to nifti conversion in captk is the orienatation. For this particualr image, Captk outputs in LPS and dcm2niix in LAS.  This is just a reorientation and the image is identical, which you can see by loading to itksnap.

So now I think the troubleshooting is why it flips the image when a LAS nifti is put into n2d

Thanks

**Comment by ashishsingh18** [comment] 2020-03-25 13:53
@chiharusako I do not know what dcm2niix is doing. If we use captk, it works as expected. I guess we can close this then?

**Comment by sarthakpati** [comment] 2020-03-25 15:11
@chiharusako and I debugged this in detail and what we concluded was the following: this issue is stemming from the fact that the image coming from dcm2niix is in a different orientation (RPI vs the original DICOM being in RAI):

```powershell
(base) PS C:\testdcmnii> Utilities.exe -inf -i .\1_TCGA-02-0003_1997.6.8_flair\000000.dcm
ITK Image information:.
Property,Value
Dimensions,3
Size,256x256x1
Total,65536
Origin,-100.000000x-115.800003x-28.100000
Spacing,0.781250x0.781250x6.500000
Component,short
Pixel Type,scalar
Directions,[1.000000x0.000000x0.000000;0.000000x1.000000x0.000000;0.000000x0.000000x1.000000]
DICOM file detected, will print out all tags from here.
[SNIP!]
(base) PS C:\testdcmnii> Utilities.exe -inf -i .\mac2_dcm2nifti_captk\dicom2nifti_20200324171917.nii.gz
ITK Image information:.
Property,Value
Dimensions,3
Size,256x256x25
Total,1638400
Origin,-100.000000x-115.800003x-67.099998
Spacing,0.781250x0.781250x6.500000
Component,float
Pixel Type,scalar
Directions,[1.000000x-0.000000x0.000000;-0.000000x1.000000x0.000000;-0.000000x-0.000000x1.000000]
(base) PS C:\testdcmnii> Utilities.exe -inf -i .\outputFromDcm2niix.nii.gz
ITK Image information:.
Property,Value
Dimensions,3
Size,256x256x25
Total,1638400
Origin,-100.000000x83.418747x-67.099998
Spacing,0.781250x0.781250x6.500000
Component,short
Pixel Type,scalar
Directions,[1.000000x-0.000000x0.000000;-0.000000x-1.000000x0.000000;0.000000x0.000000x1.000000]
```

So, in this aspect, CaPTk is doing what we would expect, i.e., write the image information from the NIfTI file and use the header information from the reference DICOM.

As per @chiharusako's suggestion, I will add a sanity check for the reference DICOM and and the NIfTI image to throw an error for the user.

**Comment by sarthakpati** [comment] 2020-03-27 12:19
@chiharusako can this be closed, now?

**Comment by chiharusako** [comment] 2020-03-27 12:54
@sarthakpati Can we make sure it doesn't say "Finished writing" when you get the error? If that's done feel free to close. Thanks so much for your help!

Current output:
> Directions are not the same.
> The reference DICOM image and image to write are not consistent.
> Finished writing the DICOM file.

Also FYI: after some reading on dcm2niix, I now understand it's by design that it does lossless rotation which is good to know. It says you can turn off the rotation but I haven't tested. Either way, voxel data is preserved so it can also always go back to the original dicom direction without losing any information.

**Comment by sarthakpati** [comment] 2020-03-27 14:57
> Can we make sure it doesn't say "Finished writing" when you get the error?

Already done and in my home directory [[ref](https://github.com/CBICA/CaPTk/pull/977/commits/0aabfb542bcb3024ba4bf049d5746ceb5303ce8b)].

**Comment by sarthakpati** [comment] 2020-03-28 18:14
@chiharusako: I am closing this ticket, please re-open if required.

**Closed by sarthakpati** 2020-03-28 18:14 UTC
Labels: Critical, Testathon-Feb-2020
