### ISSUE TITLE
Running FeatureExtraction on the command line aborts when run on a single DICOM 

### ISSUE THREAD

**Issue by waltman** [CBICA/CaPTk#829] opened 2020-02-06 20:49 UTC
**Describe the bug**
When I run the command line FeatureExtraction on the cluster for a single DICOM it aborts.

**To Reproduce**
```
$ pwd
/cbica/home/mankowsw/bin
$ ./FeatureExtraction -i /cbica/projects/Prospr/Data/HUP_Cohort_Dx/dicoms/3009186/3009186_FOR-PROCESSING_L_CC_1.dcm -m /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo/3009186_FOR-PROCESSING_L_CC_1/mask/3009186_FOR-PROCESSING_L_CC_1.mask.nii.gz -o /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo_captk -p 2_params_default_lattice.csv
Single subject computation selected.
WARNING: In /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 75
GDCMSeriesFileNames (0x3609670): /cbica/projects/Prospr/Data/HUP_Cohort_Dx/dicoms/3009186/3009186_FOR-PROCESSING_L_CC_1.dcm is not a directory

WARNING: In /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 122
GDCMSeriesFileNames (0x3609670): No Series can be found, make sure your restrictions are not too strong

terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/Core/Common/src/itkProcessObject.cxx:1424:
itk::ERROR: ExtractImageFilter(0x360e330): Input Primary is required but not set.
Aborted
```
**Expected behavior**
Based on the usage for the `-i` parameter I expected it would work with a single DICOM:

```
[  -i, --imagePaths]        Absolute path of each coregistered modality 
                            Delineate by ','
                            Example: -i c:/test1.nii.gz,c:/test2.nii.gz
                            Required for single subject mode
                            Expected Type  :: STRING
                            Expected Range :: none
```

Omid tells me that this syntax only works for nifti, and that for DICOMs it's expecting a directory instead of a single file. If that's in fact that case a) it's confusing and b) it should be documented.

**Screenshots**
N/A

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
The cluster (cubic-login4)

**Additional context**
N/A

**Comment by waltman** [comment] 2020-02-06 21:32
I made a subdirectory for each of my DICOMs, each with a symlink pointing back to the file. Then I reran FeatureExtraction with the directory instead of a file. Now it's failing with a different error message:
```
$ ./FeatureExtraction -i /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/indir_captk_202001/3009186_FOR-PROCESSING_L_CC_1 -m /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo/3009186_FOR-PROCESSING_L_CC_1/mask/3009186_FOR-PROCESSING_L_CC_1.mask.nii.gz -o /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo_captk -p 2_params_default_lattice.csv 
Images cannot handle a directory input, please use absolute paths.
```

**Comment by ashishsingh18** [comment] 2020-02-13 20:33
> 
> 
> I made a subdirectory for each of my DICOMs, each with a symlink pointing back to the file. Then I reran FeatureExtraction with the directory instead of a file. Now it's failing with a different error message:
> 
> ```
> $ ./FeatureExtraction -i /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/indir_captk_202001/3009186_FOR-PROCESSING_L_CC_1 -m /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo/3009186_FOR-PROCESSING_L_CC_1/mask/3009186_FOR-PROCESSING_L_CC_1.mask.nii.gz -o /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo_captk -p 2_params_default_lattice.csv 
> Images cannot handle a directory input, please use absolute paths.
> ```

@waltman Can you please share the inputs( on our cluster )  to try this?

@sarthakpati The Dicom read issue for Utilities is resolved and merged into master.

**Comment by waltman** [comment] 2020-02-14 14:40
I put the files in /cbica/home/mankowsw/comp_space/captk

**Comment by sarthakpati** [comment] 2020-02-14 14:44
> @sarthakpati The Dicom read issue for Utilities is resolved and merged into master.

Which commit? Was this your previous PR?

**Comment by ashishsingh18** [comment] 2020-02-14 15:49
> 
> 
> > @sarthakpati The Dicom read issue for Utilities is resolved and merged into master.
> 
> Which commit? Was this your previous PR?

This was PR #841

**Comment by sarthakpati** [comment] 2020-02-14 15:58
Perfect, then it should already be present on the cluster in my home directory:

```bash
(base) patis@/cbica/home/patis/testing/captkMyForkInstall/bin>$ ./FeatureExtraction -u
Executable Name: FeatureExtraction v1.7.7.nonRelease.20200214.70e95a8
[SNIP!]
```

@waltman, you can check from that location to see if #841 helped.

**Comment by waltman** [comment] 2020-02-14 16:13
Now I'm getting a segmentation fault:

```
$ /cbica/home/patis/testing/captkMyForkInstall/bin/FeatureExtraction -i /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1/3009186_FOR-PROCESSING_L_CC_1.dcm -m /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1_mask.nii.gz -o /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo_captk -p 2_params_default_lattice.csv
Single subject computation selected.
WARNING: In /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 75
GDCMSeriesFileNames (0x1fa12f0): /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1/3009186_FOR-PROCESSING_L_CC_1.dcm is not a directory

WARNING: In /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 122
GDCMSeriesFileNames (0x1fa12f0): No Series can be found, make sure your restrictions are not too strong

Segmentation fault
```

**Comment by sarthakpati** [comment] 2020-02-14 21:28
Dicom load is still an issue, @ashishsingh18:

```bash
(base) patis@/cbica/home/patis/testing/captkMyForkInstall/bin>$ ./Utilities -i /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1/3009186_FOR-PROCESSING_L_CC_1.dcm -o ../fe_test -d2n -d 1
WARNING: In /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 75
GDCMSeriesFileNames (0x20ce620): /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1/3009186_FOR-PROCESSING_L_CC_1.dcm is not a directory

WARNING: In /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 122
GDCMSeriesFileNames (0x20ce620): No Series can be found, make sure your restrictions are not too strong

Dicom Load Failed
```

**Comment by ashishsingh18** [comment] 2020-02-14 21:48
> 
> 
> Dicom load is still an issue, @ashishsingh18:
> 
> ```shell
> (base) patis@/cbica/home/patis/testing/captkMyForkInstall/bin>$ ./Utilities -i /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1/3009186_FOR-PROCESSING_L_CC_1.dcm -o ../fe_test -d2n -d 1
> WARNING: In /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 75
> GDCMSeriesFileNames (0x20ce620): /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1/3009186_FOR-PROCESSING_L_CC_1.dcm is not a directory
> 
> WARNING: In /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx, line 122
> GDCMSeriesFileNames (0x20ce620): No Series can be found, make sure your restrictions are not too strong
> 
> Dicom Load Failed
> ```

For Utilities d2n, we need to pass the directory containing single dicom series as input. I see you passed a dicom image. 
```
${CaPTk_InstallDir}/bin/Utlities.exe -i C:/test/dicomFolderWithSingleSubject -o C:/PathToOutputFolder/result.nii.gz -d2n 
```

**Comment by waltman** [comment] 2020-02-14 21:52
When I pass in a directory it aborts immediately:
```
$ /cbica/home/patis/testing/captkMyForkInstall/bin/FeatureExtraction -i /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1 -m /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1_mask.nii.gz -o /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo_captk -p 2_params_default_lattice.cs
Images cannot handle a directory input, please use absolute paths.
```

**Comment by ashishsingh18** [comment] 2020-02-14 21:54
> 
> 
> When I pass in a directory it aborts immediately:
> 
> ```
> $ /cbica/home/patis/testing/captkMyForkInstall/bin/FeatureExtraction -i /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1 -m /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1_mask.nii.gz -o /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo_captk -p 2_params_default_lattice.cs
> Images cannot handle a directory input, please use absolute paths.
> ```

@waltman The directory as input was only for Utilities.exe. We are yet to figure out the FeatureExtraction part.

**Comment by waltman** [comment] 2020-02-14 21:56
Interesting. Omid told me his solution to this problem was to use directories with a single file, but whenever I try it (like here) it doesn't work.

**Comment by ashishsingh18** [comment] 2020-02-24 15:41
FeatureExtraction was not handling directories as input and therefore when we gave dicom directory as input we were getting the error. I have fixed this in a separate branch 
https://github.com/ashishsingh18/CaPTk/tree/Issue_829 

A sample command line argument to test is: FeatureExtraction.exe -i C:\workspace\Data\Testathon\issue829\dcm -m C:\workspace\Data\Testathon\issue829\3009186_FOR-PROCESSING_L_CC_1_mask.nii.gz -o C:\workspace\Data\Testathon\issue829\out -p C:\workspace\Data\Testathon\issue829\2_params_default_lattice.csv

The input data for testing is located at: /cbica/home/mankowsw/comp_space/captk

With this change it loads the dicom series, but it now gives an error in GetImageReader(...) method.
@dboun can you please investigate this a bit. 

Tagging @sarthakpati

**Comment by sarthakpati** [comment] 2020-02-24 16:01
Is there anything I can do for this? From what I can see, it is squarely a DICOM-related issue.

**Comment by ashishsingh18** [comment] 2020-02-24 16:20
@sarthakpati This FeatureExtraction code was not developed to handle dicom. It was not accepting directories as input as I mentioned in my previous comment. I have made that change. Dicom series is getting loaded now. But there are errors thrown further down in FeatureExtraction. It is no longer a dicom issue. 

If you can investigate it would help. @dboun will also investigate this later.

**Comment by sarthakpati** [comment] 2020-02-24 16:23
The commit where you have made this change [[ref](https://github.com/ashishsingh18/CaPTk/commit/910718807c825744fc191d00be2068641b4d5da0)] this will not work because FE does a lot of sanity checks on the input images afterwards.

**Comment by ashishsingh18** [comment] 2020-02-24 16:32
That is the only change needed for dicom loading. Once a dicom image is loaded, all else should work as for nifti.

**Comment by sarthakpati** [comment] 2020-02-24 16:38
You are right, the entire reading is offloaded to the ```cbica::ReadImage``` routine and all sanity checks happen after that [[ref](https://github.com/CBICA/CaPTk/blob/master/src/applications/FeatureExtraction/src/FeatureExtraction.cxx#L119)]. As long as that function works, FE will also work.

**Comment by sarthakpati** [comment] 2020-02-24 16:51
The problem is here: https://github.com/CBICA/CaPTk/blob/master/src/applications/FeatureExtraction/src/FeatureExtraction.cxx#L495 

The image getting passed to ```cbica::GetExtractedImages``` is ```NULL```, thereby initiating the crash.

**Comment by ashishsingh18** [comment] 2020-02-24 17:15
Correct. And if we step into the GetExtractedImage method, the actual error occurs in GetImageReader method during a sanity check.

It looks like the data is not correct.

When I load the input and mask into mitk, I can see that the dimensions and origin of mask do not match with the input. Here is how it looks when loaded into MITK

![image](https://user-images.githubusercontent.com/43445206/75174795-368bc400-56ff-11ea-9990-0c0210b84f88.png)

**Comment by sarthakpati** [comment] 2020-02-24 17:23
> When I load the input and mask into mitk

We need to ensure that this works here, not in any other application. 

The function ```cbica::ReadImage``` calls on the ```DicomIOManager``` for DICOMs [[ref](https://github.com/CBICA/CaPTk/blob/master/src/cbica_toolkit/src/cbicaITKSafeImageIO.h#L788)]; ergo, the issue is ```DicomIOManager```. 

The data is completely fine, because on the CaPTk GUI, it bypasses that class and calls ```ConversionFrom2Dto3D``` [[ref](https://github.com/CBICA/CaPTk/blob/master/src/view/gui/fMainWindow.cpp#L1045)] and it works perfectly fine.

**Comment by ashishsingh18** [comment] 2020-02-26 00:50
There is no issue with DicomIOManager. The responsibility of Dicom IO module, including DicomIOManager, is to read Dicom data and return an ITK image in the format that CaPTk needs i.e. ImageTypeFloat3D. It also tells via a boolean variable if the Dicom reading succeeded or failed. All of this happens via the cbica::ReadImage adapter. The Dicom module doesn't change the image properties such as origin, spacing, etc. In this case(after my changes in branch: https://github.com/ashishsingh18/CaPTk/tree/Issue_829) the Dicom reading succeeds, so I don't understand how this is a Dicom reading issue anymore. What happens afterwards and how the read image is handled is the responsibility of the application in this case FeatureExtraction.

That said, in this case the input data that Walt is using seems bad. MITK screenshot was attached in one of my earlier comments to show that the data that Walt was loading had different image properties. It is clearly seen in the MITK screenshot. Slicer, MITK and other popular medical imaging application are always good benchmarks for comparison.

The screenshot that you attached in the previous comment is not using the data that Walt raised the issue about. Please try with the data that Walt shared at: /cbica/home/mankowsw/comp_space/captk 
Both these data don't load in CaPTK even via the GUI.

@dboun can you please double check this?

**Comment by dboun** [comment] 2020-02-26 03:43
I will be able to contribute more to the discussion after the changes get through and I can build on debug in linux. 

That been said, @ashishsingh18 can you make clearer what you want me to try?

Also are we positive that this is not a different manifestation of issue #859? I understand that there is a good chance it's not, but I can't help but notice that both issues are basically about dicoms, that are loosely related to dimensionality/sanity-checks.

**Comment by ashishsingh18** [comment] 2020-02-26 04:28
@dboun This issue is unrelated to #859. Here the data is bad, meaning the image properties of the 2 input datasets are different. #859 is about rounding error in the sanity checks. Could you please investigate the root cause of this issue?
Please do your investigations with the data that Walt shared and with my changes from branch: https://github.com/ashishsingh18/CaPTk/tree/Issue_829
You will need debugging abilities on your machine...

**Comment by sarthakpati** [comment] 2020-02-26 13:38
> Both these data don't load in CaPTK even via the GUI

I may be missing something here but the datasets in ```/cbica/home/mankowsw/comp_space/captk``` (both the DICOM image and NIfTI mask) loads up fine on the GUI (on the 1.7.6 release):

![image](https://user-images.githubusercontent.com/11719673/75349502-e6ce0980-5872-11ea-9903-116a590837a8.png)

The fact that the mask and image are oriented differently is on whoever prepared the data, of course.

What I was talking about in my [previous comment](https://github.com/CBICA/CaPTk/issues/829#issuecomment-590449168) was that the DICOM parsing engine in CaPTk is not able to handle any of the mammogram images (even the LIBRA sample ones). The reason why it works on the GUI is because it bypasses the DICOM parsing.

**Comment by ashishsingh18** [comment] 2020-02-26 14:54
One of the data is an image(dicom data) and the other(nifti one) is a mask. If you try to load both of them together they don't load. In the images above, you have loaded the mask as an image. Try to load the dicom data as an image and the mask as an ROI and see the result. This is how Walt is loading the data in FeatureExtraction. 

Here is what I get on 1.7.6

![image](https://user-images.githubusercontent.com/43445206/75356079-6eb91100-587d-11ea-84c6-e88fd00eb8d4.png)

**Comment by sarthakpati** [comment] 2020-02-26 15:14
That is correct behavior since we do not want people to mix the image and mask types, i.e., the image and mask need to be in the same physical space (see [testMask.nii.gz](https://github.com/CBICA/CaPTk/files/4256465/testMask.nii.gz) attached).

The issue is that even if the mask was valid, FE won't be able to read the DICOM image because of what I pointed out.

**Comment by ashishsingh18** [comment] 2020-02-26 15:16
> 
> 
> > Both these data don't load in CaPTK even via the GUI
> 
> I may be missing something here but the datasets in `/cbica/home/mankowsw/comp_space/captk` (both the DICOM image and NIfTI mask) loads up fine on the GUI (on the 1.7.6 release):
> 
> ![image](https://user-images.githubusercontent.com/11719673/75349502-e6ce0980-5872-11ea-9903-116a590837a8.png)
> ![image](https://user-images.githubusercontent.com/11719673/75349874-87bcc480-5873-11ea-87e4-095c6f24a255.png)
> 
> The fact that the mask and image are oriented differently is on whoever prepared the data, of course.
> 
> What I was talking about in my [previous comment](https://github.com/CBICA/CaPTk/issues/829#issuecomment-590449168) was that the DICOM parsing engine in CaPTk is not able to handle any of the mammogram images (even the LIBRA sample ones). The reason why it works on the GUI is because it bypasses the DICOM parsing.

I am able to load all LIBRA sample DICOM data via GUI in CaPTk. Here's a screenshot. 
![image](https://user-images.githubusercontent.com/43445206/75357544-88f3ee80-587f-11ea-9420-093e116840a6.png)

Btw you have also loaded mammography dicom data that Walt shared. You even posted a screenshot of it in your[ previous comment.](https://github.com/CBICA/CaPTk/issues/829#issuecomment-591430264) 

Also, we are not bypassing the DICOM reading at all in GUI. If we had bypassed dicom reading via GUI, we would not be able load the dicoms even via the GUI.

**Comment by ashishsingh18** [comment] 2020-02-26 15:34
> 
> 
> That is correct behavior since we do not want people to mix the image and mask types, i.e., the image and mask need to be in the same physical space (see the example [testMask.nii.gz](https://github.com/CBICA/CaPTk/files/4256465/testMask.nii.gz) I created on CaPTk).
> 
> The issue is that even if the mask was valid, FE won't be able to read the DICOM image because of what I pointed out.



> 
> 
> That is correct behavior since we do not want people to mix the image and mask types, i.e., the image and mask need to be in the same physical space (see the example [testMask.nii.gz](https://github.com/CBICA/CaPTk/files/4256465/testMask.nii.gz) I created on CaPTk).
> 
> The issue is that even if the mask was valid, FE won't be able to read the DICOM image because of what I pointed out.

So the data that Walt is trying is indeed bad. 

Btw, have you tried with the fix I had in: https://github.com/ashishsingh18/CaPTk/tree/Issue_829

If there is another data or workflow that doesn't work, we should open another issue on Github and deal with that separately.

**Comment by sarthakpati** [comment] 2020-02-26 15:44
Please read [this](https://github.com/CBICA/CaPTk/issues/829#issuecomment-590449168) comment again. I never said that we are bypassing DICOM reading. I said that we are bypassing using the ```DicomIOManager``` class for 2D images.

The fix in your branch doesn't work, either.

> So the data that Walt is trying is indeed bad.

The mask+image combination that @waltman is trying is **definitely** invalid. But my point is that even if he tried to use a correctly initialized mask (as I did in my [last comment](https://github.com/CBICA/CaPTk/issues/829#issuecomment-591477589)), it would break because of the aforementioned reason.

**Comment by ashishsingh18** [comment] 2020-02-26 15:46
Btw, I just tried FE with the changes I had in branch: https://github.com/ashishsingh18/CaPTk/tree/Issue_829

and with the testMask.nii.gz you shared( [here ](https://github.com/CBICA/CaPTk/issues/829#issuecomment-591477589)) and it seems to work...

Not sure if the output it produces is correct but it definitely doesn't crash..

**Comment by sarthakpati** [comment] 2020-02-27 15:38
If that is the case, then it might be better to do this change on the ```cbica::ReadImage``` level so that the user-facing CLI is the same, i.e., they pass a single NIfTI file OR the first DICOM file in a series. Passing a folder creates potential confusion.

**Comment by sarthakpati** [comment] 2020-02-29 23:56
[This commit](https://github.com/sarthakpati/CaPTk/commit/207bbbaedfd4bb5c608540d4731cee6399837174) is the appropriate fix for this issue.

**Closed** 2020-03-05 14:01 UTC
Labels: Major, Testathon-Feb-2020

**Comment by waltman** [comment] 2020-03-06 18:21
> The fact that the mask and image are oriented differently is on whoever prepared the data, of course.

As far as I can tell this is a feature of the Texture Pipeline code. It orients all the images and masks to face the same direction.

**Comment by waltman** [comment] 2020-03-06 18:25
Is this fix testable now on the cluster?

**Comment by sarthakpati** [comment] 2020-03-06 18:31
You can access the updated executable in ```~patis/testing/captkMyForkInstall/bin``` for testing.
