### ISSUE TITLE
Perfusion derivatives changes direction

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#1009] opened 2020-04-28 01:03 UTC
**Describe the bug**
Perfusion derivatives doesn't maintain the direction of the image

**To Reproduce**
I put an example input and results in:
/cbica/home/sakoc/comp_space/lab/captk/1.7.6/perfd

$/cbica/software/lab/captk/centos7/1.7.6/bin/captk PerfusionDerivatives -i ABGX_2016.09.27_perf_LPS.nii.gz -e 45 -p 1 -pH 1 -r 1 -o $PWD

Please note the change in the direction:

$ /cbica/home/patis/testing/captkMyForkInstall/bin/Utilities -inf -i ABGX_2016.09.27_perf_LPS.nii.gz 
ITK Image information:.
Property,Value
Dimensions,4
Size,128x128x20x45
Total,14745600
Origin,-85.231522x-164.112946x-17.219128x0.000000
Spacing,1.718750x1.718750x5.000000x1.000000
Component,float
Pixel Type,scalar
**Directions,[0.984808x0.173648x0.000000;-0.173648x0.984808x0.000000;-0.000000x-0.000000x1.000000;0.000000x0.000000x0.000000]**

$ /cbica/home/patis/testing/captkMyForkInstall/bin/Utilities -inf -i PH.nii.gz 
ITK Image information:.
Property,Value
Dimensions,3
Size,128x128x20
Total,327680
Origin,-85.231522x-164.112946x-17.219128
Spacing,1.718750x1.718750x5.000000
Component,float
Pixel Type,scalar
**Directions,[1.000000x-0.000000x0.000000;-0.000000x1.000000x0.000000;-0.000000x-0.000000x1.000000]**

**Expected behavior**
The derivatives should be aligned with the input image

**Screenshots**
Grey is the input, red/yellow is the ap-RCBV

![image](https://user-images.githubusercontent.com/47368657/80435340-3c05b600-88ca-11ea-8019-d3dfa40d74c2.png)

**CaPTk Version**
1.7.6 on cluster

**Desktop (please complete the following information):**
cubic-login3

**Comment by sarthakpati** [comment] 2020-04-28 03:23
As long as all references to ```GetOneVolumeImage``` in the ```PerfusionDerivatives``` class are replaced with ```cbica::GetExtractedImages```, this issue will be fixed. The problem is in [this](https://github.com/CBICA/CaPTk/blob/master/src/applications/PerfusionDerivatives.h#L167) line. 

**We have tested utilities that should be used instead of per-class implementations.**

There is, however, a much bigger concern in this class. At [this](https://github.com/CBICA/CaPTk/blob/master/src/applications/PerfusionDerivatives.h#L375) location, the **6th** timepoint is getting processed. Why? Perhaps @saimarathore can shed some light on this.

Tagging @ashishsingh18 @MarkBergman-cbica

**Comment by sarthakpati** [comment] 2020-04-28 12:13
Hey @chiharusako, I have added an intermittent fix for this issue and it should be available on my home directory on the hash ```ad26e01```.

**Comment by sarthakpati** [comment] 2020-04-28 13:24
@chiharusako has confirmed that https://github.com/sarthakpati/CaPTk/commit/ad26e014947707dbb8b85db66e04d8decd59e534 fixes this issue. 

However, I am keeping this issue open since my previous comment still stands.

> As long as all references to `GetOneVolumeImage` in the `PerfusionDerivatives` class are replaced with `cbica::GetExtractedImages`, this issue will be fixed. The problem is in [this](https://github.com/CBICA/CaPTk/blob/master/src/applications/PerfusionDerivatives.h#L167) line.
> 
> **We have tested utilities that should be used instead of per-class implementations.**
> 
> There is, however, a much bigger concern in this class. At [this](https://github.com/CBICA/CaPTk/blob/master/src/applications/PerfusionDerivatives.h#L375) location, the **6th** timepoint is getting processed. Why? Perhaps @saimarathore can shed some light on this.
> 
> Tagging @ashishsingh18 @MarkBergman-cbica

**Comment by ashishsingh18** [comment] 2020-04-28 21:57
@sarthakpati Can we open another issue for the time point issue and close this one if the perfusion derivatives direction issue is fixed?
Tagging @saimarathore @chiharusako

**Comment by sarthakpati** [comment] 2020-04-28 23:03
Done.

**Closed by sarthakpati** 2020-04-28 23:03 UTC
