### ISSUE TITLE
Command line load sample data Unit Test

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#540] opened 2019-06-05 15:56 UTC
**Is your feature request related to a problem? Please describe.**
See issue #539 
Some sample data files failed to load when other files were present

**Describe the solution you'd like**
Have a unit test that tests loading images from sample data sets

**Additional context**
![EGFR_sample_sata](https://user-images.githubusercontent.com/20047333/58971158-d166fb80-8788-11e9-9ba6-8799079427ea.PNG)

**Comment by sarthakpati** [comment] 2019-06-06 00:32
Duplicate of #539; closing this and continuing discussion there.

**Closed by sarthakpati** 2019-06-06 00:32 UTC
