### ISSUE TITLE
[LINUX] CAPTK_BUILD_OPTION builds "Release" regardless of selection (in build, not superbuild)

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#804] opened 2020-01-23 04:49 UTC
**Describe the bug**
_title_
Probably related to issue #775 (were the fixes for this ever upstreamed?). Regardless, #775 was for the superbuild, this is for the build.

**To Reproduce**
1. Do "Debug" superbuild. There is no CAPTK_BUILD_OPTION, just set CMAKE_BUILD_TYPE to "Debug" manually.
2. Open cmake in build configure+generate etc
3. Set CMAKE_BUILD_TYPE to "Debug" manually to see it change (this is not needed, but it will make the problem more clear)
4. Set CAPTK_BUILD_OPTION to "DEVELOPER_MODE". 
5. Configure+generate. CMAKE_BUILD_TYPE becomes "Release", instead of remaining Debug.

**CaPTk Version**
1.7.5

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Comment by sarthakpati** [comment] 2020-07-09 14:02
Duplicate of #775

**Closed by sarthakpati** 2020-07-09 14:02 UTC
Labels: Linux, Minor
