### ISSUE TITLE
BreastSegmentation does not work when i load mammogram image

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#466] opened 2019-05-01 16:01 UTC
loaded one mammogram image from sample data
(case1.dcm)
Selected BreastSegmentation from the applications menu. Got the following error message.

![image](https://user-images.githubusercontent.com/38562504/57026899-e04a1380-6c08-11e9-9fc1-bbf61a433419.png)

**Comment by sarthakpati** [comment] 2019-05-06 14:26
Related to #467 and #468

**Comment by sarthakpati** [comment] 2019-05-06 14:27
Duplicate of #467 and #468

**Comment by sarthakpati** [comment] 2019-05-07 14:17
Tracking this issue on #464 and closing this

**Closed by sarthakpati** 2019-05-07 14:17 UTC
