### ISSUE TITLE
Lung Field Segmentation opens up blank help page

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#386] opened 2019-03-13 16:25 UTC
**Describe the bug**
When trying to start the Lung Field Segmentation application without the proper images, the message "Load two images with first being the CT and second being the PET image." and then proceeds to open a blank help dialog.

**To Reproduce**
1. Load ACC0_flair + ROI
2. Change modality to PET
3. Launch Lung Field Segmentation from Applications dropdown

**Expected behavior**
A populated help dialog appears

**Screenshots**
![Screen Shot 2019-03-13 at 12 25 28 PM](https://user-images.githubusercontent.com/9388076/54296335-1bc24d00-458b-11e9-9bbe-1c8a82a8d809.png)

**CaPTk Version**
1.6.2 Beta

**Desktop (please complete the following information):**
 - OS: macOS 10.13.2

**Comment by PhucNgo1711** [comment] 2019-03-13 16:53
This was caused by html files not packaged properly

**Comment by sarthakpati** [comment] 2019-03-14 12:02
> This was caused by html files not packaged properly

This is correct; not an issue with SBRT.

**Comment by PhucNgo1711** [comment] 2019-03-25 19:23
This should be fixed now

**Closed by PhucNgo1711** 2019-03-25 19:23 UTC
Labels: bug, macOS
