### ISSUE TITLE
Dicom to Nifti conversion doesn't work for DTI and Perfusion

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#1240] opened 2020-08-10 13:21 UTC
**Describe the bug**
In the dicom to conversion in Utilities, the 4th dimension is not recognized for both DTI and Perfusion and .bval and .bvec is not extracted for DTI.

**To Reproduce**

Input and output are at the below location. I also made conversion outputs using dcm2niix for comparison. The output of dcm2niix is what is expected.

```
dir="/cbica/home/sakoc/comp_space/lab/captk/180b/d2n"
for m in dti perf; do

    fin=`ls -1 $dir/dcm_$m/* | head -n 1`      # <----- getting one filename as Utilities -d2n input is one dicom, not dicom directory
    /cbica/software/lab/captk/centos7/1.8.0.Beta/bin/Utilities \
         -i $fin \
         -o $dir/out_captk/$m.nii.gz \
	 -d2n

    /cbica/home/sakoc/software/dcm2niix/v1.0.20190410/dcm2niix \
         -o out_dcm2niix -z y -f $m dcm_$m
    
done
```
output:
```
$ for i in out_*/*nii.gz; do echo $i,`Utilities -i $i -inf | grep Dimensions`,`Utilities -i $i -inf | grep Size`; done
out_captk/dti.nii.gz,Dimensions,3,Size,128x128x442
out_captk/perf.nii.gz,Dimensions,3,Size,128x128x900
out_dcm2niix/dti.nii.gz,Dimensions,4,Size,128x128x34x13   # <-- this is what is expected
out_dcm2niix/perf.nii.gz,Dimensions,4,Size,128x128x20x45  # <-- this is what is expected
```

**Expected behavior**
DTI dicoms produce a 4D nifti and 2 directional files (.bval and .bvec) files
Perfusion dicoms produce a 4D nifti file.

**CaPTk Version**
1.8.0.Beta

**Desktop (please complete the following information):**
 - OS: centos7

**Comment by sarthakpati** [comment] 2020-08-10 13:50
I guess this is a duplicate of #1030

**Comment by chiharusako** [comment] 2020-08-10 14:00
It's not. That one was nifti to dicom, which we decided that we don't need. This is from Dicom to Nifti, which I'd think is more important, unless the group decides otherwise...

**Comment by sarthakpati** [comment] 2020-08-10 14:07
Oops, sorry, you are right.

**Comment by ashishsingh18** [comment] 2020-08-10 20:27
Utilities uses our own dicom module which doesn't support perfusion and DTI dicoms. Looks like dcm2niix is able to do what are looking for. We should use that for dicom to nifti conversions. We will need to bundle dcm2niix.

**Comment by sarthakpati** [comment] 2020-09-02 19:51
This fix has broken normal DICOM to NIfTI conversion when the output has been specified as a file.

**Comment by ashishsingh18** [comment] 2020-09-02 20:01
Broken on GUI?

Can you share the dicom data?

**Comment by sarthakpati** [comment] 2020-09-02 20:18
Take any DICOM, it is replicable there:

```powershell
Utilities.exe -i "C:\\CaPTk_Data\LIBRA_1.6.0\3\Case3.dcm" -o "case3.nii.gz" -d2n
Please pass the path to the output folder where you want to save the nifti file.
```

**Comment by ashishsingh18** [comment] 2020-09-02 20:42
It is working for me both from GUI as well as from Utilities. I guess the docs for Utilities were not updated with our move to dcm2niix. Now we need to specify the output folder name and **not** the nifti file name for output. dcm2niix figures out the name itself.

So please un-comment the part you commented and try giving path to an output folder on the CLI.

**Comment by sarthakpati** [comment] 2020-09-02 20:46
> It is working for me both from GUI as well as from Utilities. I guess the docs for Utilities were not updated with our move to dcm2niix. Now we need to specify the output folder name and **not** the nifti file name for output. dcm2niix figures out the name itself.

Right.

> 
> So please un-comment the part you commented and try giving path to an output folder on the CLI.

Nope, it needs to be fixed in a separate PR to ensure the user can specify the output **file**. For structural DICOMs, the user **should** be able to specify a **single** file and not have to deal with a NIfTI with a random file name and corresponding JSON.

**Comment by ashishsingh18** [comment] 2020-09-02 21:09
> 
> 
> > It is working for me both from GUI as well as from Utilities. I guess the docs for Utilities were not updated with our move to dcm2niix. Now we need to specify the output folder name and **not** the nifti file name for output. dcm2niix figures out the name itself.
> 
> Right.
> 
> > So please un-comment the part you commented and try giving path to an output folder on the CLI.
> 
> Nope, it needs to be fixed in a separate PR to ensure the user can specify the output **file**. For structural DICOMs, the user **should** be able to specify a **single** file and not have to deal with a NIfTI with a random file name and corresponding JSON.

It is not a random file name. dcm2niix is using a smart method using info from dicom to create the name. Such naming schemes are way better than user specified random names.

I don't think changing this is necessary. User knows what output directory is being specified and can always look there for the output.

**Comment by sarthakpati** [comment] 2020-09-02 23:23
> > > It is working for me both from GUI as well as from Utilities. I guess the docs for Utilities were not updated with our move to dcm2niix. Now we need to specify the output folder name and **not** the nifti file name for output. dcm2niix figures out the name itself.
> > 
> > 
> > Right.
> > > So please un-comment the part you commented and try giving path to an output folder on the CLI.
> > 
> > 
> > Nope, it needs to be fixed in a separate PR to ensure the user can specify the output **file**. For structural DICOMs, the user **should** be able to specify a **single** file and not have to deal with a NIfTI with a random file name and corresponding JSON.
> 
> It is not a random file name. dcm2niix is using a smart method using info from dicom to create the name. Such naming schemes are way better than user specified random names.
> 
> I don't think changing this is necessary. User knows what output directory is being specified and can always look there for the output.

I do not agree with this folder-major naming schema. It creates unnecessary folders during a processing routine, which can be easily avoided by simply checking if the user is specifying a file in the beginning of the conversion.

**Comment by sarthakpati** [comment] 2020-09-03 03:35
https://github.com/sarthakpati/CaPTk/commit/8beaf9c810b9ab202de08be9e10e588a4de15990 addresses my concerns. Closing.

**Closed by sarthakpati** 2020-09-03 03:35 UTC
