### ISSUE TITLE
[MAC-GUI] Image Co-registration Output Issue

### ISSUE THREAD

**Issue by rongguangwang** [CBICA/CaPTk#855] opened 2020-02-15 14:47 UTC
**Describe the bug**
After the affine or rigid registration, there's no output images in the specified directory. However, the progress bar at the bottom right shows that "registration complete - 100%".

**To Reproduce**
1. Launch the "Registration" dialog from the "Preprocessing" menu.
2. Customize the parameters (Metrics, Radius and Iterations) as needed.
3. Specify the moving images and their respective output images.
4. Click on 'Register'.
5. See error.

**Expected behavior**
The output image is saved in the specified locations.

**Screenshots**
<img width="852" alt="Screen Shot 2020-02-15 at 09 43 39" src="https://user-images.githubusercontent.com/39313320/74589905-a7343180-4fd7-11ea-9c40-6bd4fb12b285.png">

**CaPTk Version**
CaPTk_1.7.6

**Desktop**
 - OS: macOS
 - Version: 10.15.3 (19D76)

**Comment by sarthakpati** [comment] 2020-05-14 14:19
Duplicate of #768

**Comment by PhucNgo1711** [comment] 2020-05-14 22:22
```
sh: /Applications/CaPTk_1.8.0.nonRelease.20200514.cb1d4d07.app/Contents/Resources/bin/greed: No such file or directory
Something went wrong when calling Greedy Affine.
```
Hmm looks like greedy was not packaged into CaPTk. Looking into the cause of this.

**Comment by sarthakpati** [comment] 2020-05-15 00:31
This should be coming in from Preprocessing.

**Comment by sarthakpati** [comment] 2020-05-15 02:44
Hey @PhucNgo1711, I think I figured this out. If we look at where greedy is [getting installed](https://github.com/CBICA/greedy/blob/ee848107a52af5f145e1b2ea3cd3f74f92056352/CMakeLists.txt#L205), it shows that it is going into ```bin```. It should be in the same location as the ```Preprocessing``` executable. Can you check where it is in the package?

**Comment by PhucNgo1711** [comment] 2020-05-15 02:46
This is not `GreedyRegistration` right?

**Comment by sarthakpati** [comment] 2020-05-15 11:18
That is correct. We are only using ```greedy```.

**Comment by sarthakpati** [comment] 2020-05-15 12:07
If it makes debugging this easier, I am pretty sure this can be replicated from the ```Preprocessing``` CLI as well. But the first point is to figure out where ```greedy``` gets installed. I think the quickest way to solve this would be not use the CMake configuration from the [```greedy``` subproject](https://github.com/CBICA/greedy/) and to initialize the CLI in the [```Preprocessing``` project](https://github.com/CBICA/CaPTk/tree/master/src/applications/Preprocessing)

**Comment by sarthakpati** [comment] 2020-05-15 13:06
Hey @PhucNgo1711, can you check my fork now? I think I may have fixed this.

**Comment by PhucNgo1711** [comment] 2020-05-15 14:21
I'm testing the fix now.

**Comment by PhucNgo1711** [comment] 2020-05-15 16:11
I still don't have the greedy executable in bin (the same level as Preprocessing)
Based on the logs it looks like greedy is built. I'm trying to figure out why it's not in bin.

**Comment by sarthakpati** [comment] 2020-05-15 17:45
[This line](https://github.com/sarthakpati/CaPTk/blob/master/src/applications/Preprocessing/CMakeLists.txt#L81) should be taking care of this and putting it in ```bin```.

**Comment by sarthakpati** [comment] 2020-05-17 22:12
Any update?

**Comment by PhucNgo1711** [comment] 2020-05-17 22:38
I'm having `redefinition` errors if I make the changes you have in the Preprocessing CMakeList file. Your build worked so I was going to grab the installer from your build, but the mac installer created from your build corrupted, and this is not an Azure self-hosted issue. I'm debugging this.

**Comment by sarthakpati** [comment] 2020-05-18 12:03
Okay, let me know if I can help with something.

**Comment by PhucNgo1711** [comment] 2020-05-18 23:57
This is now fixed on mac @sarthakpati. `greedy` is available in `bin`.

**Comment by sarthakpati** [comment] 2020-05-19 01:06
Awesome!

**Comment by sarthakpati** [comment] 2020-05-19 12:06
To be clear, it was https://github.com/sarthakpati/CaPTk/commit/d04a5920f48df87ccdfed05c2369e9aa7e1dc977 that fixed it. It is already in the master. I am closing this out and will re-open if someone reports it again.

**Closed** 2020-05-19 17:14 UTC
Labels: GUI, Testathon-Feb-2020
