### ISSUE TITLE
Libra (Batch mode) not working

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#465] opened 2019-05-01 15:59 UTC
i got the following error message when i launched batch mode of LIBRA. 
![image](https://user-images.githubusercontent.com/38562504/57026759-88131180-6c08-11e9-97ac-3f4724dc269b.png)

1.7.0
Windows 7

**Comment by ashishsingh18** [comment] 2019-05-02 16:18
Duplicate of #475

**Comment by sarthakpati** [comment] 2019-05-07 14:12
Fixed.

**Closed by sarthakpati** 2019-05-07 14:12 UTC
